project:
  type: website

website:
  title: "Sierra Leone Wildlife"
  navbar:
    right:
      - about.qmd
      - text: blog posts
        href: index.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: minty
    css: styles.css

editor: visual

