project:
  type: website
  output-dir: docs

website:
  title: "Sierra Leone Wildlife"
  navbar:
    right:
      - text: about
        href: index.qmd
      - text: Wildlife blog
        href: blog.qmd
      - text: Wildlife resources
        href: wildlife_resources.qmd
      - text: Stats blog
        href: statsblog.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: minty
    css: styles.css

navbar:
    background: "blue"
    
editor: visual

